In [103]:
from tensorflow.keras.preprocessing.text import one_hot

In [104]:
sent=[
    'I love milk',
    'She went to school this morning',
    'the cup of tea is very hot',
    'And his name is John Cena'
]

In [105]:
voc_size = 10000

In [106]:
one_hot_rep = [one_hot(word,voc_size) for word in sent]
one_hot_rep

[[2071, 1350, 6131],
 [9229, 4939, 4935, 367, 9642, 9128],
 [8535, 4699, 7681, 3385, 6073, 877, 4680],
 [9884, 1889, 1718, 6073, 3200, 3716]]

In [107]:
from tensorflow.keras.layers import Embedding
from tensorflow.keras.utils import pad_sequences
from tensorflow.keras.models import Sequential

In [108]:
import numpy as np
sent_len = 8
embedded_docs = pad_sequences(one_hot_rep, padding='pre', maxlen=sent_len)
embedded_docs

array([[   0,    0,    0,    0,    0, 2071, 1350, 6131],
       [   0,    0, 9229, 4939, 4935,  367, 9642, 9128],
       [   0, 8535, 4699, 7681, 3385, 6073,  877, 4680],
       [   0,    0, 9884, 1889, 1718, 6073, 3200, 3716]])

In [109]:
dim=10
model=Sequential()
model.add(Embedding(voc_size, dim, input_length=sent_len))
model.compile('adam','mse')

In [110]:
model.summary()

Model: "sequential_12"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ embedding_5 (Embedding)         │ ?                      │   0 (unbuilt) │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 0 (0.00 B)

 Trainable params: 0 (0.00 B)

 Non-trainable params: 0 (0.00 B)

In [111]:
model.predict(embedded_docs)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 95ms/step


array([[[ 0.02962669,  0.04091403,  0.02022472, -0.04360783,
          0.03314045,  0.01688043, -0.03917529,  0.04326056,
         -0.0186401 ,  0.03035331],
        [ 0.02962669,  0.04091403,  0.02022472, -0.04360783,
          0.03314045,  0.01688043, -0.03917529,  0.04326056,
         -0.0186401 ,  0.03035331],
        [ 0.02962669,  0.04091403,  0.02022472, -0.04360783,
          0.03314045,  0.01688043, -0.03917529,  0.04326056,
         -0.0186401 ,  0.03035331],
        [ 0.02962669,  0.04091403,  0.02022472, -0.04360783,
          0.03314045,  0.01688043, -0.03917529,  0.04326056,
         -0.0186401 ,  0.03035331],
        [ 0.02962669,  0.04091403,  0.02022472, -0.04360783,
          0.03314045,  0.01688043, -0.03917529,  0.04326056,
         -0.0186401 ,  0.03035331],
        [-0.00390758,  0.00705834,  0.00954109,  0.02910978,
         -0.00827668, -0.03501459,  0.03750772, -0.00218434,
          0.00836345,  0.01860623],
        [ 0.04935655,  0.02496606,  0.04944099,  0.0

In [115]:
single_sequence = np.array([embedded_docs[0]])
single_sequence

array([[   0,    0,    0,    0,    0, 2071, 1350, 6131]])

In [116]:
model.predict(single_sequence)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 38ms/step


array([[[ 0.02962669,  0.04091403,  0.02022472, -0.04360783,
          0.03314045,  0.01688043, -0.03917529,  0.04326056,
         -0.0186401 ,  0.03035331],
        [ 0.02962669,  0.04091403,  0.02022472, -0.04360783,
          0.03314045,  0.01688043, -0.03917529,  0.04326056,
         -0.0186401 ,  0.03035331],
        [ 0.02962669,  0.04091403,  0.02022472, -0.04360783,
          0.03314045,  0.01688043, -0.03917529,  0.04326056,
         -0.0186401 ,  0.03035331],
        [ 0.02962669,  0.04091403,  0.02022472, -0.04360783,
          0.03314045,  0.01688043, -0.03917529,  0.04326056,
         -0.0186401 ,  0.03035331],
        [ 0.02962669,  0.04091403,  0.02022472, -0.04360783,
          0.03314045,  0.01688043, -0.03917529,  0.04326056,
         -0.0186401 ,  0.03035331],
        [-0.00390758,  0.00705834,  0.00954109,  0.02910978,
         -0.00827668, -0.03501459,  0.03750772, -0.00218434,
          0.00836345,  0.01860623],
        [ 0.04935655,  0.02496606,  0.04944099,  0.0